# Generated by Django 6.0.6 on 2026-07-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tazkera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, null=True, verbose_name='اسم و تخلص')),
                ('father_name', models.CharField(max_length=100, null=True, verbose_name='اسم پدر')),
                ('grandfather_name', models.CharField(max_length=100, null=True, verbose_name='اسم پدرکلان')),
                ('place_of_birth', models.CharField(max_length=100, null=True, verbose_name='محل تولد')),
                ('date_of_birth', models.CharField(max_length=10, null=True, verbose_name='تاریخ تولد')),
                ('marital_status', models.CharField(max_length=30, null=True, verbose_name='حالت مدنی')),
                ('mother_language', models.CharField(max_length=50, null=True, verbose_name='زبان مادری')),
                ('permanent_address', models.CharField(max_length=100, null=True, verbose_name='سکونت اصلی')),
                ('current_address', models.CharField(max_length=100, null=True, verbose_name='سکونت فعلی')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='شماره تماس')),
                ('height', models.CharField(max_length=20, null=True, verbose_name='قد')),
                ('eye_color', models.CharField(max_length=50, null=True, verbose_name='رنگ چشم')),
                ('eyebrow', models.CharField(max_length=50, null=True, verbose_name='رنگ ابرو')),
                ('face_color', models.CharField(max_length=50, null=True, verbose_name='رنگ چهره')),
                ('hair_color', models.CharField(max_length=50, null=True, verbose_name='رنگ مو')),
                ('special_marks', models.CharField(max_length=50, null=True, verbose_name='نشانه های دیگر')),
                ('id_type', models.CharField(choices=[('passport', 'پاسپورت اقامتی'), ('sarshomari', 'برگه سرشماری'), ('amayesh', 'کارت آمایش'), ('daftarche', 'دفترچه اقامت ویژه')], max_length=20, null=True, verbose_name='مدرک اقامتی')),
                ('id_number', models.CharField(max_length=50, null=True, verbose_name='شماره مدرک')),
                ('full_name_r', models.CharField(max_length=255, null=True, verbose_name='اسم و تخلص اقارب')),
                ('father_name_r', models.CharField(max_length=100, null=True, verbose_name='اسم پدر اقارب')),
                ('grandfather_name_r', models.CharField(max_length=100, null=True, verbose_name='اسم پدرکلان اقارب')),
                ('tazkera_id', models.CharField(max_length=100, null=True, verbose_name='شماره تذکره')),
                ('tz_volumes', models.CharField(max_length=50, null=True, verbose_name='جلد')),
                ('tz_page', models.CharField(max_length=50, null=True, verbose_name='صفحه')),
                ('reg_id', models.CharField(max_length=50, null=True, verbose_name='شماره ثبت')),
                ('tz_year', models.CharField(max_length=50, null=True, verbose_name='سال')),
                ('e_tz_id', models.CharField(max_length=50, null=True, verbose_name='شماره تذکره الکترونیکی')),
                ('kindship', models.CharField(max_length=50, null=True, verbose_name='نوع قرابت')),
                ('issue_date', models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ثبت')),
            ],
            options={
                'verbose_name': 'فرم تذکره',
                'verbose_name_plural': 'فرم تذکره ها',
            },
        ),
    ]
