# Generated by Django 6.0.6 on 2026-07-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TazkeraForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tazkera',
            name='services',
            field=models.ManyToManyField(blank=True, to='TazkeraForm.service', verbose_name='نوع خدمات'),
        ),
    ]
