# Generated by Django 6.0.6 on 2026-07-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TazkeraForm', '0002_service_tazkera_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'نوع خدمت', 'verbose_name_plural': 'نوع خدمات'},
        ),
        migrations.RemoveField(
            model_name='tazkera',
            name='e_tz_id',
        ),
        migrations.RemoveField(
            model_name='tazkera',
            name='reg_id',
        ),
        migrations.RemoveField(
            model_name='tazkera',
            name='tz_page',
        ),
        migrations.RemoveField(
            model_name='tazkera',
            name='tz_volumes',
        ),
        migrations.RemoveField(
            model_name='tazkera',
            name='tz_year',
        ),
        migrations.AddField(
            model_name='tazkera',
            name='marriage_id',
            field=models.CharField(max_length=50, null=True, verbose_name='شماره نکاح خط رسمی'),
        ),
        migrations.AddField(
            model_name='tazkera',
            name='phone_r',
            field=models.CharField(max_length=50, null=True, verbose_name='شماره تماس اقارب'),
        ),
        migrations.AlterField(
            model_name='tazkera',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='شماره تماس'),
        ),
    ]
