# Generated by Django 6.0.6 on 2026-07-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TazkeraForm', '0003_alter_service_options_remove_tazkera_e_tz_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tazkera',
            name='father_name_r',
            field=models.CharField(max_length=100, null=True, verbose_name='اسم پدر نماینده'),
        ),
        migrations.AlterField(
            model_name='tazkera',
            name='full_name_r',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم و تخلص نماینده'),
        ),
        migrations.AlterField(
            model_name='tazkera',
            name='grandfather_name_r',
            field=models.CharField(max_length=100, null=True, verbose_name='اسم پدرکلان نماینده'),
        ),
        migrations.AlterField(
            model_name='tazkera',
            name='phone_r',
            field=models.CharField(max_length=50, null=True, verbose_name='شماره تماس'),
        ),
    ]
